    # .github/workflows/main.yml
    name: Use Secrets

    on:
      workflow_dispatch: # Allows manual triggering of the workflow

    jobs:
      access-secret:
        runs-on: ubuntu-latest
        steps:
          - name: Use Secret and Access Secrets
            env:
              API_TEST_PKEY: ${{ secrets.API_TEST_PKEY }},
              API_LIVE_PKEY: ${{ secrets.API_LIVE_PKEY }},
              API_TEST_SKEY: ${{ secrets.API_TEST_SKEY }},
              API_LIVE_SKEY: ${{ secrets.API_LIVE_SKEY }}
            run: |
              echo "The secret is : $API_LIVE_SKEY"
              node -e "console.log(process.env.API_LIVE_SKEY)"
              
