    # .github/workflows/main.yml
    name: Use Secrets

    on:
      workflow_dispatch: # Allows manual triggering of the workflow

    jobs:
      access-secret:
        runs-on: ubuntu-latest
        steps:
          - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: '18.16.0'
          - name: Install dependencies
            run: |
                node --version
                npm install
        
          - name: Use Secrets and Access Secrets
            env:
              API_TEST_PKEY: ${{ secrets.API_TEST_PKEY }},
              API_LIVE_PKEY: ${{ secrets.API_LIVE_PKEY }},
              API_TEST_SKEY: ${{ secrets.API_TEST_SKEY }},
              API_LIVE_SKEY: ${{ secrets.API_LIVE_SKEY }}
            run: |
              npm run start
              echo "The Test Publishable Key is : $API_TEST_PKEY"
              node -e "console.log(process.env.API_TEST_PKEY)"
              echo "The Live Publishable Key is : $API_LIVE_PKEY"
              node -e "console.log(process.env.API_LIVE_PKEY)"
              echo "The Test Secret is : $API_TEST_SKEY"
              node -e "console.log(process.env.API_TEST_SKEY)"
              echo "The Live Secret is : $API_LIVE_SKEY"
              node -e "console.log(process.env.API_LIVE_SKEY)"
              
